version: '3.9'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=videoscraper
      - POSTGRES_PASSWORD=videoscraper
      - POSTGRES_DB=videoscraper
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/:/var/lib/postgresql/data/pgdata/

  backend:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://videoscraper:videoscraper@db:5432/videoscraper

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: ["python", "-m", "celery", "-A", "videoscraper", "worker", "-l", "info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://videoscraper:videoscraper@db:5432/videoscraper
